# Generated by Django 4.1.7 on 2023-04-04 20:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_files_uploaded_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='uploaded_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
