# Generated by Django 4.1.7 on 2023-04-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_files_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='user',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
