# Generated by Django 4.1.7 on 2023-04-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('conf_password', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField(max_length=10)),
            ],
        ),
    ]
